CREATE TABLE IF NOT EXISTS Listings (id INTEGER NOT NULL auto_increment , sellerName VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, sellingPrice INTEGER NOT NULL, sqFootage INTEGER NOT NULL, bedrooms INTEGER NOT NULL, areaZip INTEGER NOT NULL, image VARCHAR(255) NOT NULL, hotAndCold TINYINT(1) DEFAULT false, createdAt DATETIME NOT NULL, updatedAt, listingDetails DATETIME NOT NULL, listingDetails TEXT, PRIMARY KEY (id));

INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Zach Taylor", "zachttaylor00@gmail.com", "200000", "1000", "3", "64102", "https://photos.zillowstatic.com/p_e/ISn2gkr9nvd54n1000000000.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33", "Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Anthony Martin", "amartin@gmail.com", "500000", "4000", "3", "64102", "https://wdcimagestorageprodeast.blob.core.windows.net/mls009/Web/3602879_103459083_1.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33", "Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting! ");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Sanjib Biswas", "sbiswas@gmail.com", "300000", "2000", "3", "64102", "https://wdcimagestorageprodeast.blob.core.windows.net/mls009/Web/3602879_103459083_1.jpg", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Brooks Riekhof", "briekhof@gmail.com", "750000", "6000", "5", "64102", "https://an.rdcpix.com/2310391423/013d0ce25fe49965cac96d48212612f9e-f1xd-w480_h480_q80.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
 
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Paul Smith", "psmith@gmail.com", "250000", "2400", "3", "64116", "https://wp-tid.zillowstatic.com/16/shutterstock_12227221-c9ca3f.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Salley Williams", "swilliams@gmail.com", "900000", "7000", "6", "64116", "https://storage.googleapis.com/idx-acnt-gs.ihouseprd.com/AR475730/file_manager/SS%20Images/ANYHOUSE%20USA%205-3%20(400X400)-min.jpg", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting! ");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Mary Douglas", "mdouglas@gmail.com", "270000", "2000", "3", "64116", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPTvxTXTneHFVy3KDu_HM078pJVCmBkHSQWCiLYhcK7_FrNrK3&s", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Steve Moore", "smoore@gmail.com", "530000", "3200", "4", "64116", "https://pi.movoto.com/p/611/2193461_0_v63Rn2_p.jpeg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet. ");
 
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Doug Clark", "dclark@gmail.com", "360000", "2800", "3", "64106", "https://pi.movoto.com/p/311/10292355_0_fmJ7E3_p.jpeg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("William Samuels", "wSam@gmail.com", "820000", "6500", "6", "64106", "http://4.bp.blogspot.com/_ExW047CJ9z0/TOv1eraIgLI/AAAAAAAAAoo/K3PMszATFZA/s1600/Wallcate.com%2B-%2BReal%2BEstate%2BVilla%2BHouse%2B%252823%2529.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Ellen Moss", "emoss@gmail.com", "180000", "2500", "3", "64106", "https://www.myroof.co.za/prop_static/MR148642/p/b/699038.JPG", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Allen Hamilton", "ahamilton@gmail.com", "480000", "3900", "4", "64106", "https://d4gb4hun5n6dm.cloudfront.net/uploads/listings/2019/02/7daed14ca4bb85f_t_w_1280_h_1024.jpg", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
 
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Brad Stevens", "bstevens@gmail.com", "780000", "6800", "7", "64124", "https://i.ytimg.com/vi/ipBUaKDvFRw/maxresdefault.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Kim Bradley", "kbradley@gmail.com", "450000", "3800", "4", "64124", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVGHP1sGM4XD9ektFq6q2quElmmZOV4fiVeD3aktlo7atVAttO&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Keith Duncan", "kduncan@gmail.com", "300000", "2500", "5", "64124", "https://d19r2wl60x3cy9.cloudfront.net/uploads/listings/2019/05/f031dc2f281c3db_t_w_800_h_600.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Ben Simmons", "bsimmons@gmail.com", "710000", "7100", "6", "64124", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHq6y0FDBRaVBA9wycdMmo-8J4TIIwqLo1c50AUn4zmVKYJXJi&s", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
  
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Beth Any", "bany@gmail.com", "320000", "1800", "3", "64105", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0CUu95BeZwPK7kwg_biEDnK7veSJF4iZkf-jWSokyrfvjSxf0&s", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Ken Bone", "kbone@gmail.com", "860000", "4800", "5", "64105", "https://d2nqc4o7q9rmvr.cloudfront.net/uploads/listings/2019/11/b36b3714b92913e_t_w_800_h_600.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Martha May", "mmay@gmail.com", "260000", "3000", "4", "64105", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2zTmX9M5EoeBOG5nHi-ZQ3WFpcX4s2yozbgjQ2nFud55w0pUj&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Kevin Smith", "ksmith@gmail.com", "900000", "5800", "5", "64105", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPXYz0Ne-qrKDAEtoPIaTVOPCiNCv_emLiLgmwjF0mYld8iVVi&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
  
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Jan Smith", "jsmith@gmail.com", "376000", "1800", "3", "64123", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2GwxD03H1PTpAhTIK49aKyO4EzTdXDAu0F5BRcgkpgj7R7c2WUw&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Donald Fitzpatrick", "donfitz@gmail.com", "490000", "3100", "5", "64123", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTESY2A0NLnTmuEmm8ZGyP4bmWf4xsiS30R0osLXGV2GpErTnUs&s", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Cindy Lou", "clou@gmail.com", "529000", "4000", "5", "64123", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqRcs6ChurKpClMDTb_W7pp7tu4SMVXWoT4lzjvsltv7udfPgj&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Chris Topher", "christ@gmail.com", "493000", "4900", "6", "64123", "https://i.ebayimg.com/images/g/nuQAAOSwxW9dtE-a/s-l800.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
  
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Ivan Rodriguez", "irod@gmail.com", "895000", "5800", "7", "64115", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc7qhdudxBuYR8odBRpRMyYuz3QnzCIBlplkIL7JsCCBujVByZ&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Sam Gamgee", "sgim@gmail.com", "25000", "700", "3", "64115", "https://i.kinja-img.com/gawker-media/image/upload/s--BkvOYYIx--/c_scale,f_auto,fl_progressive,q_80,w_800/18l20h0295y5fjpg.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Greg Christopher", "gchristopher@gmail.com", "268000", "2000", "3", "64115", "https://prppublicstore.blob.core.windows.net/live-za-images/property/107/38/5976107/images/property-5976107-81986115.jpg", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Blake Griffin", "bgriffin@gmail.com", "237000", "4800", "4", "64115", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNtSJFXf5YAKV8x9db28IPvIbNlHBYZNhBIQJ9SYo5yzwk1cem&s", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
  
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Natalie OReilly", "nato@gmail.com", "620000", "4500", "4", "64117", "https://i2.au.reastatic.net/800x600/0c7e2cda03405f6f251093c9b74dd43dd54288ec65a79401b1bbe69bf1e44b3d/main.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Wes Green", "wgreen@gmail.com", "896000", "4900", "4", "64117", "https://i2.au.reastatic.net/800x600/2d3e759f51f14c35085487a704d4b282983844a83a3ca68ed48f4bbce099cf22/main.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Jackson Wheeler", "jwheeler@gmail.com", "710000", "4900", "5", "64117", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0wikIavT2dmngnztk-ctDesm_DAl31Ctencg3tBh-KCUDj2kU&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Colby Bryant", "cbryant@gmail.com", "579000", "4200", "3", "64117", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkq9-9mshKAE1I_ZfdLEH89j3NAzHxvE4U3Lm4yQW13WE2Aoo8&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
  
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Michelle Clark", "mclark@gmail.com", "651000", "3800", "4", "64120", "https://images.realestateview.com.au/pics/943/42-knightsbridge-avenue-glenwood-nsw-2768-real-estate-photo-1-large-11731943.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Justin Thomas", "jthomas@gmail.com", "484000", "2900", "3", "64120", "https://i3.au.reastatic.net/800x600/d97523a3310c2630c5a53cd4ce318d18a68df9fe2632e269bc9cb29850fc7a42/main.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Nate Parker", "nparker@gmail.com", "238000", "1900", "2", "64120", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgh96NWhnooUHY2SG4UO6iG9_7w3zBWqrxK-GexPFZhUVx_YGW&s", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Pat Mahomes", "pmahomes@gmail.com", "477000", "4550", "3", "64120", "https://i3.au.reastatic.net/800x600/d8f2adad0e00d54ce9a16b9bdaa42630af96e088d38993438e29025db2a5b3f5/main.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
 
  
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Quin Williams", "qwilliams@gmail.com", "556000", "3800", "4", "64121", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA2_NgD8utecfsTBPUoqLAKgFDp1GNWS6l5NZ8-RF3htCwjqqr&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Julie McGraw", "jmcgraw@gmail.com", "383000", "2000", "3", "64121", "https://img.othsolutions.com.au/resize/upload/d81b10d06d3f27a0f1b9ad7d946262aa/70e5adf39718eef2d04af203c9a0b161.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Cole Bates", "cbates@gmail.com", "433000", "2600", "4", "64121", "https://www.phillymag.com/wp-content/uploads/sites/3/2019/07/house-for-sale-abington-midcentury-split-level-exterior-front-brightmls.jpeg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Henry Woods", "hwoods@gmail.com", "333000", "6540", "5", "64121", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7T5OTnEcRePDTwE6Vf9ICbS_MGqA9XO7sHLu9qLfbizLmLZAh&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");

  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Peter Parker", "spidey@gmail.com", "46000", "2100", "3", "64127", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaaeLc90DUFL0pG3GKpf5gtX8jhinOUaasrM-ymYqxpxbtoFFQ&s", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("First Last", "name@gmail.com", "258000", "2730", "3", "64127", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSQhPzeMj7FonRQOxlh6Yy6wwB75H4_3a4OwH_cbe0M7e0UjrS&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Jason Carson", "json@gmail.com", "885000", "5800", "6", "64127", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY_FK9jwxqsXpTIUBySSbvQibougW3h1QPqPnwpYIjc9Fz1X7_&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.")
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Mike Vick", "mvick@gmail.com", "593000", "5180", "5", "64127", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB0fae2n09Y45vGySbkXy6P-SNNKwX6oP36y8R4_fuOMe16GIrbQ&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
  
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Warren Carmichael", "wcar@gmail.com", "654300", "3800", "4", "64101", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUcDxbtrYb6ung5Fiw9oDQ8PvObcKgdZBLCYU15wz-3RmIkFOu&s", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Karen Neil", "kneil@gmail.com", "158000", "2740", "3", "64101", "https://res-3.cloudinary.com/beycome/image/upload/f_auto,q_auto,t_thumbnail-property/Single-Family-For-Sale-by-Owner-455-Northeast-75th-Street-Miami-FL-33138-df6d9.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Courtney Hall", "chall@gmail.com", "254000", "2600", "3", "64101", "https://ap.rdcpix.com/436b369aee62cad11ba1ba0aac7cd6b6l-m2087075892xd-w480_h480_q80.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Burt Mitchell", "bmitchell@gmail.com", "583000", "4300", "4", "64101", "https://ap.rdcpix.com/688873421/607083cb2845d11ccfd3b6f8af292260l-m0xd-w480_h480_q80.jpg", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
  
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Jillian Ward", "jward@gmail.com", "539800", "3900", "4", "64108", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSqC9WVYaxi8cBabm89b2heJ5tDMLWE0P-7o63tAvmoCLEJscf&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Charcandrick West", "cwest@gmail.com", "697000", "5300", "6", "64108", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzNf0YSmBDaDP6Pck3foK-EYoutp0S7rC8L8ZkVVzslEIPeh7fHg&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Alan Jackson", "ajackson@gmail.com", "893000", "7700", "3", "64108", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkGz-NBNL7qN2I6sAvXCXD6VT8o6a2Vmj27rrNrkK_P7_gG283-A&s", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Tom Ryan", "tryan@gmail.com", "483000", "3370", "4", "64108", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwxL1AQZlZ19fhvOyuqpFyGoBDSGKuC4IPKs2a2QOd-72RzZ0N&s", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Charming Tudor home in sought after Brookside neighborhood. Updated kitchen with granite countertops, cabinetry includes rollout shelves. Formal dining room and breakfast area. Huge master suite with private bath and walk in closet.");
  
  
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Priest Holmes", "pholmes@gmail.com", "865300", "4800", "5", "66101", "https://an.rdcpix.com/2310391423/013d0ce25fe49965cac96d48212612f9e-f1xd-w480_h480_q80.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Rare Morningside opportunity on large corner lot in the heart of Brookside! Home features beautiful woodwork, molding & stunning Jerusalem Stone on fireplace, kitchen, & baths. Hardwood floors throughout, Savoy light fixtures, custom cabinets & exposed brick in kitchen adds to the charm. Newer windows, copper plumbing, whirlpool tub, so many updates!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Arya Stark", "astark@gmail.com", "253000", "1500", "2", "66101", "https://fshouses.com/wp-content/uploads/2019/11/DSC_9573-680x510.jpg", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods.");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Ronald McDonald", "mcds@gmail.com", "573000", "4190", "5", "66101", "https://d3g2g127w3rg4d.cloudfront.net/CWBR/2180/8540/21808540-1350745abf1e193.jpg", true, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Amazing Home with an amazing display of care. Features include bright updated kitchen and charming bath. Master bedroom has rehabbed sleeping porch with additional wardrobe for extended closet space. Enclosed front porch with welcoming large entry with great lighting!");
INSERT INTO Listings (sellerName, email, sellingPrice, sqFootage, bedrooms, areaZip, image, hotAndCold, createdAt, updatedAt, listingDetails) VALUES ("Erin Henry", "ehenry@gmail.com", "367500", "2470", "3", "66101", "https://storage.googleapis.com/idx-acnt-gs.ihouseprd.com/AR959498/file_manager/Saved%20Searches/ANYHOUSE%20USA%204-1%20(400X400)-min.jpg", false, "2019-12-18 18:46:33", "2019-12-18 18:46:33","Fantastic kitchen updates w/custom cabinets, pantry, SS appliances, granite & Loads of storage. Main level boasts hardwood floors, half bath, enclosed porch for bonus living space. Original trim & style w/all of today's colors. Spacious master bedroom features large sun deck, walk-in cedar closets & hardwoods."); 
  